config/routes.rb
Rails.application.routes.draw do
  devise_for :teams, controllers: {
    sessions:      'teams/sessions',
    passwords:     'teams/passwords',
    registrations: 'teams/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "samples#index"
  resources :calendars
  resources :samples
  resources :users, only: [:show]
  resources :teams, only: [:show]
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :move_to_sign_in

  def index
    if user_signed_in?
      @user = User.find(current_user.id)
      @events = UserEvent.where(user_id: @user.id)
    elsif team_signed_in?
      @team = Team.find(current_team.id)
      @events = TeamEvent.where(team_id: @team.id)
    end
  end

  def show
    if user_signed_in?
      @event = UserEvent.find(params[:id])
      @events = UserEvent.where(user_id: current_user.id).where(day: @event.start_time.day).order('start_time ASC')
    elsif team_signed_in?
      @event = TeamEvent.find(params[:id])
      @events = TeamEvent.where(team_id: current_team.id).where(day: @event.start_time.day).order('start_time ASC')
    end
  end

  def new
    if user_signed_in?
      @event = UserEvent.new
    elsif team_signed_in?
      @event = TeamEvent.new
    end
  end

  def create
    if user_signed_in?
      @event = UserEvent.new(user_event_params)
      if @event.valid?
        @event.day = @event.start_time.day
        @event.save
        redirect_to calendars_path
      else
        flash[:alert] = 'タイトルは50文字以内で入力してください'
        render 'calendars/new'
      end
    elsif team_signed_in?
      @event = TeamEvent.new(team_event_params)
      if @event.valid?
        @event.day = @event.start_time.day
        @event.save
        redirect_to calendars_path
      else
        flash[:alert] = 'タイトルは20文字以内で入力してください'
        render 'calendars/new'
      end
    end
  end

  def edit
    if user_signed_in?
      @event = UserEvent.find(params[:id])
    elsif team_signed_in?
      @event = TeamEvent.find(params[:id])
    end
  end

  def update
    if user_signed_in?
      @event = UserEvent.find(params[:id])
      @event.update(user_event_params)
      if @event.valid?
        @event.day = @event.start_time.day
        @event.save
        redirect_to calendars_path
      else
        flash[:alert]
        render 'calendars/edit'
      end
    elsif team_signed_in?
      @event = TeamEvent.find(params[:id])
      @event.update(team_event_params)
      if @event.valid?
        @event.day = @event.start_time.day
        @event.save
        redirect_to calendars_path
      else
        flash[:alert]
        render 'calendars/edit'
      end
    end
  end

  def destroy
    if user_signed_in?
      @event = UserEvent.find(params[:id])
      if @event.destroy
        redirect_to calendars_path
      else
        flash[:alert] = '削除に失敗しました'
        @events = UserEvent.where(user_id: current_user.id).where(day: @event.start_time.day).order('start_time ASC')
        render 'calendars/show'
      end
    elsif team_signed_in?
      @event = TeamEvent.find(params[:id])
      if @event.destroy
        redirect_to calendars_path
      else
        flash[:alert] = '削除に失敗しました'
        @events = TeamEvent.where(team_id: current_user.id).where(day: @event.start_time.day).order('start_time ASC')
        render 'calendars/show'
      end
    end
  end

  private

  def user_event_params
    params.require(:user_event).permit(:title, :start_time, :body, :day).merge(user_id: current_user.id)
  end

  def team_event_params
    params.require(:team_event).permit(:title, :start_time, :body, :day).merge(team_id: current_team.id)
  end

  def move_to_sign_in
    return unless !user_signed_in? && !team_signed_in?

    redirect_to new_user_session_path
    flash[:alert] = 'ログインしてください'
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/edit.html.erb
<%= render 'layouts/sidebar' %>
<div class="col-sm-9">
  <h1 class="text-center">予定を編集</h1>
  <div class="col-sm-8 col-sm-offset-2">
    <%= form_with model: @event, url: calendar_path, local: true do |f| %>
      <div class="red">
        <%= render "users/shared/error_messages", resource: @event %>
      </div>

      <div class="form-group">
        <%= f.label :タイトル %><br>
        <%= f.text_field :title, placeholder: "タイトルを入力してください(最大20文字まで)", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :開始時刻 %><br>
        <%= f.datetime_field :start_time %>
      </div>

      <div class="form-group">
        <%= f.label :詳細 %><br>
        <%= f.text_field :body ,placeholder: "詳細を入力してください", class: "form-control"%>
      </div>

      <div class="submit">
        <%= f.submit "変更する",class: "btn btn-black" %>
      </div>
    <% end %>
  </div>
</div>

app/views/calendars/index.html.erb
<%= render 'layouts/sidebar' %>
<div class="col-sm-9">
  <h1 class="text-center">カレンダー</h1>

  <%= month_calendar events: @events do |date,events| %>
    <%= date.day %>
    <% events.each do |event| %>
      <div>
        <%= link_to "#{event.title}", calendar_path(event) %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/calendars/new.html.erb
<%= render 'layouts/sidebar' %>
<div class="col-sm-9">
  <h1 class="text-center">予定を作成</h1>
  <div class="col-sm-8 col-sm-offset-2">
    <%= form_with model: @event, url: calendars_path, local: true do |f| %>
      <div class="red">
        <%= render "users/shared/error_messages", resource: @event %>
      </div>

      <div class="form-group">
        <%= f.label :タイトル %><br>
        <%= f.text_field :title, placeholder: "タイトルを入力してください(最大20文字まで)", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :開始時刻 %><br>
        <%= f.datetime_field :start_time %>
      </div>

      <div class="form-group">
        <%= f.label :詳細 %><br>
        <%= f.text_field :body ,placeholder: "詳細を入力してください", class: "form-control"%>
      </div>

      <div class="submit">
        <%= f.submit "作成する",class: "btn btn-black" %>
      </div>
    <% end %>
  </div>
</div>

app/views/calendars/show.html.erb
<%= render 'layouts/sidebar' %>
<div class="col-sm-9">
  <h1 class="text-center">一日の予定一覧</h1>
    <% @events.each do |event| %>
      <div class="col-sm-8 col-sm-offset-2">
        <h3>タイトル:  <%= event.title %></h3>
        <% unless event.body == "" %>
          <p>詳細:  <%= event.body%></p>
        <% end %>
        <p>開始時刻:  <%= event.start_time.to_s(:datetime_jp)%></p>
        <div class="btn btn-warning">
          <%= link_to "編集する", edit_calendar_path(event) %>
        </div>
        <div class="btn btn-danger">
          <%= link_to "削除する", calendar_path(event), method: :delete %>
        </div>
      </div>
    <% end %>
</div>