config/routes.rb
Rails.application.routes.draw do
  devise_for :teams, controllers: {
    sessions:      'teams/sessions',
    passwords:     'teams/passwords',
    registrations: 'teams/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "samples#index"
  resources :calendars
  resources :samples
  resources :users, only: [:show]
  resources :teams, only: [:show]
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default navbar-fixed-top top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"data-toggle="collapse"data-target="#navbarEexample8">
				<span class="sr-only"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
      <% if !user_signed_in? && !team_signed_in? %>
        <%= link_to "Calendar", root_path, class:"navbar-brand"%>
      <% else %>
        <%= link_to "Calendar", calendars_path, class:"navbar-brand"%>
        <% if user_signed_in? %> 
          <%= link_to "#{current_user.nickname}さん", calendars_path, class:"navbar-brand"%>
        <% elsif team_signed_in? %>
          <%= link_to "#{current_team.name}さん", calendars_path, class:"navbar-brand"%>
        <% end %>
      <% end %>
		</div>
		
		<div class="collapse navbar-collapse" id="navbarEexample8">
			<% if !user_signed_in? && !team_signed_in? %>
        <button type="button" class="btn btn-info navbar-btn navbar-right space">
          <%= link_to "サインアップ", new_user_registration_path %>
        </button>
        <button type="button" class="btn btn-info navbar-btn navbar-right space">
          <%= link_to "ログイン", new_user_session_path %>
        </button>
        <button type="button" class="btn btn-info navbar-btn navbar-right space">
          <%= link_to "チーム作成", new_team_registration_path %>
        </button>
        <button type="button" class="btn btn-info navbar-btn navbar-right space">
          <%= link_to "チームに参加", new_team_session_path %>
        </button>
      <% elsif user_signed_in? %>
        <button type="button" class="btn btn-info navbar-btn navbar-right space">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </button>
      <% elsif team_signed_in? %>
        <button type="button" class="btn btn-info navbar-btn navbar-right space">
          <%= link_to "チームログアウト", destroy_team_session_path, method: :delete %>
        </button>
      <% end%>
		</div>
	</div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-sm-3 silver height bottom">
  <div class="sidebar_fixed">
    <% if user_signed_in? %>
      <ul class="padding-top ">
        <div class="space">
          <%= link_to "カレンダー", calendars_path %>
        </div>
        <div class="space">
          <%= link_to "予定を作成", new_calendar_path %>
        </div>
      </ul>
    <% elsif team_signed_in? %>
      <ul class="padding-top ">
        <div class="space">
          <%= link_to "カレンダー", calendars_path %>
        </div>
        <div class="space">
          <%= link_to "予定を作成", new_calendar_path %>
        </div>
      </ul>
    <% else %>
      <ul class="padding-top ">
        <div class="space">
          <%= link_to "カレンダー(サンプル)", samples_path %>
        </div>
        <div class="space">
          <%= link_to "予定を作成(サンプル)", new_sample_path %>
        </div>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calender</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script src="http://code.jquery.com/jquery.js"></script>
    <%= render 'layouts/header' %>
    <%# <% flash.each do |message_type, message| %> 
      <%# <div class="alert alert-<%= message_type%><%# "> %>
      <%# <%= message %><%#/div> %>
    <%# <% end%> 
    <%= yield %>
  </body>
</html>